[changelog]
protect_breaking_commits = true

commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^deprecated", group = "Deprecated" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^doc", group = "Documentation" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactors" },
    { message = "^style", group = "Styling" },
    { message = "^test", group = "Testing" },
    { message = "^chore\\(release\\): prepare for", skip = true },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^ci", skip = true },
    { body = ".*security", group = "Security" },
    { message = "^revert", group = "Reverted" },
    { message = "^.*", group = "Miscellaneous" },
]
