[package]
name = "apt-edsp"
version = "0.1.0"
edition = "2021"

[dependencies]
rfc822-like = "0.2.2"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.22"
nom = "7"

[dev-dependencies]
indoc = "2"
