name: CI

permissions:
  pull-requests: write
  contents: write

on:
  push:
  pull_request:
    types:
      - closed

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build, test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Check code formatting
        run: cargo fmt --check
      - name: Run clippy
        uses: auguwu/clippy-action@1.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    needs: build
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    env:
      is_merged_release_pr: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'refs/heads/release-plz-') }}
    steps:
      # Generating a GitHub token, so that PRs and tags created by
      # the release-plz-action can trigger actions workflows.
      - name: Generate GitHub token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - run: echo "Is merged release PR = $is_merged_release_pr"
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        with:
          # Run `release` if we just merged a release-plz PR, else run `release-pr`
          command: ${{ github.env.is_merged_release_pr && 'release' || 'release-pr' }}
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
